"""Type stubs for the crypto C extension module."""

import numpy.typing as npt
import numpy as np

def simple_cryptor_encrypt_bytes(buf: bytearray, key: npt.NDArray[np.uint8]) -> None: ...
def simple_cryptor_decrypt_bytes(buf: bytearray, key: npt.NDArray[np.uint8]) -> None: ...
def xxtea_encrypt_blocks(data: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32], full_word_count: int) -> None: ...
def xxtea_decrypt_blocks(data: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32], full_word_count: int) -> None: ...
def xxtea_encrypt_block(v: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32], n: int) -> None: ...
def xxtea_decrypt_block(v: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32], n: int) -> None: ...
def xxtea_encrypt_block_fixed(v: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32]) -> None: ...
def xxtea_decrypt_block_fixed(v: npt.NDArray[np.uint32], key: npt.NDArray[np.uint32]) -> None: ...
